fix: handled the validateDOMNesting error
PolicyEngine/policyengine-app pull request #1082
Opened 2024-01-01 01:28 UTC by dotslashbit

## Description

Please provide a summary of the changes and which issue is fixed. Please include relevant motivation and context.

closes #1065 

## Changes
There were nesting p elements, I have modified the structure of the elements to get the same output but now the outer element is a div

## Screenshots

### Before
<img width="1710" alt="Screenshot 2024-01-01 at 6 53 26 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/fd54186d-b165-4776-ac4b-7e1a072cf2e6">

### After
<img width="1710" alt="Screenshot 2024-01-01 at 6 54 10 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/40c5adc0-c33d-47fd-a446-c0a744301b42">

## Tests

Please describe how the change has been tested.

2024-01-02 21:42 UTC, anth-volk commented
This would fix the issue; however, at the moment, BottomCarousel is very much engineered to accept only text, a clear limitation of the component. Could you change the `bottomText` prop name to `bottomElements` or something similar and ensure that the app utilizes that prop properly (I think it's only invoked in two or three spots at the moment)? Otherwise I think it's unclear that that prop is being displayed as a div that other tags can sit within.

2024-01-02 21:42 UTC, anth-volk requested changes
Please see commentary above

2024-01-04 03:11 UTC, dotslashbit commented
@anth-volk I have updated the code, let me know if there's any correction to be made

2024-01-04 20:52 UTC, anth-volk requested changes
Thanks again, @dotslashbit. I left one comment that I should've flagged last time and neglected that is meant to keep the functioning of this prop standardized. After that, I think it's good to merge.

2024-01-04 20:52 UTC, anth-volk commented on src/pages/household/output/HouseholdOutput.jsx
> +          bottomElements="PolicyEngine results may not constitute exact tax liabilities or benefit entitlements."
```suggestion
          bottomElements={<p>PolicyEngine results may not constitute exact tax liabilities or benefit entitlements.</p>}
```

2024-01-04 20:52 UTC, anth-volk commented on src/pages/household/output/HouseholdOutput.jsx
> +          bottomElements="PolicyEngine results may not constitute exact tax liabilities or benefit entitlements."
Apologies, should've also mentioned this before in the earlier review.

2024-01-05 01:46 UTC, dotslashbit commented
@anth-volk did the required changes, let me know if there's anything needed to be done

2024-01-05 04:13 UTC, anth-volk approved these changes
This is perfect, thanks so much @dotslashbit!

2024-01-05 04:14 UTC, merged