fix: cursor now changes to pointer when hovering
PolicyEngine/policyengine-app pull request #1113
Opened 2024-01-05 02:14 UTC by dotslashbit

## Description

fixes #890 

## Changes

updated the cursor now change to pointer when hover over the enable

## Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/46224156/4e5db4e1-e2fd-4e7d-8a91-10a2b6f9022c

2024-01-08 20:20 UTC, anth-volk requested changes
Thanks so much, @dotslashbit. I did leave one change request, but otherwise your efforts are much appreciated.

2024-01-08 20:20 UTC, anth-volk commented on src/pages/policy/PolicyRightSidebar.jsx
Unfortunately, this change will work only for boolean parameter changes, but not for value changes (e.g., https://policyengine.org/us/policy?reform=43695&focus=policyOutput.policyBreakdown&region=us&timePeriod=2024&baseline=2). Could you also add the styling on post-change line 162?

2024-01-09 04:34 UTC, dotslashbit commented
@anth-volk  I have added the styling, please check and let me know if there's any changes needed

2024-01-09 19:58 UTC, anth-volk approved these changes
Thanks @dotslashbit, this looks perfect. Merging.

2024-01-09 19:59 UTC, merged