Repair Reproduce in Python code
PolicyEngine/policyengine-app pull request #1249
Opened 2024-01-22 13:50 UTC by anth-volk

## Description

Fixes #1179, fixes #653, fixes #1248. Previously, the code included in the `Reproduce in Python` page of the policy reform calculator displayed non-working code. 

## Changes

This PR repairs this code by ensuring that US contexts (those with region of "us" and "enhanced_us") have additional lines aimed at ensuring the baseline policy sets the parameter `simulation.use_reported_state_income_tax` to true. It also shifts from using `calculate_dataframe` to `calc` in order to prevent bugs associated with that operation, and removes a trailing semicolon from a different component. Finally, it ensures that the `year` property of the displayed code updates properly, and for policies with multiple parameters of different time periods, it ensures that `use_reported_state_income_tax` applies to the entire simulated period by iterating over the parameter list and setting its time period based upon that.

## Screenshots

A Loom video is available at https://www.loom.com/share/795b31c44954498f829a5690ebd53250?sid=a1d64b72-cdd0-49b6-9b66-b085ab5a5444.

## Tests

None have been included.

2024-01-22 16:25 UTC, MaxGhenis requested changes
Thanks - does this also affect the household side, with and/or without a reform?

2024-01-22 16:25 UTC, MaxGhenis commented on src/pages/policy/output/PolicyReproducibility.jsx
> +    `    parameters.simulation.reported_state_income_tax.update(start=instant("${earliestStart}"), stop=instant("${latestEnd}"), value=True)`,
could we break these up so they fit on 80-character lines?

2024-01-22 16:25 UTC, MaxGhenis commented on src/pages/policy/output/PolicyReproducibility.jsx
> +  const isCountryUS =
also apply on line 76
```suggestion
  const US_REGIONS = ["us", "enhanced_us"];
  const isCountryUS = US_REGIONS.includes(metadata.countryId); 
```

2024-01-22 21:12 UTC, anth-volk commented
To answer your broader question, this does not affect the household side, as I was unaware of a need to change the code there, as well. Is that necessary?

2024-01-22 21:17 UTC, MaxGhenis commented
Oops you're right, household side is fine.

2024-01-23 19:06 UTC, anth-volk commented
I've spent quite a bit of time working on something way too nitpicky. At certain times, when editing a parameter with a name that's longer than 80 characters, the manual breaks embedded in this code don't actually limit the parameter name. I've written some code to fix this, but it's very finicky and I'm not in love with it. Can we push this, even though it doesn't fully accomplish the goal of splitting long parameter names into 80-char segments, instead of using the spaghetti I've written?

2024-01-23 19:51 UTC, MaxGhenis commented
Yes that was just for that one line if it was easy!

2024-01-23 20:04 UTC, merged