Not all authors are displayed properly on Research page's authors filter tab
PolicyEngine/policyengine-app pull request #1585
Opened 2024-04-11 13:55 UTC by NishantSatere

## Description

Fixes #1554

## Changes

implemented a scrollable checkbox list and also added a feature where opening one checkbox closes the others

##Screenshots

https://github.com/PolicyEngine/policyengine-app/assets/100207648/f359f978-e5ac-4c9e-b5f8-035f36525143

2024-04-11 13:59 UTC, anth-volk commented
Just one thing before I review later today: Could you change the title to what this does? E.g., "Display all authors on Research page's authors filter tab." Your current format is what we use for the issues, not the fixes

2024-04-11 14:11 UTC, NishantSatere commented
I am getting this error
<img width="1166" alt="Screenshot 2024-04-11 at 7 40 47 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/100207648/b703fe9c-89e6-4fb5-b7e0-65d02167df56">

2024-04-11 14:18 UTC, NishantSatere commented
yes!

2024-04-11 14:32 UTC, anth-volk commented
In that case, could you just run `npm run fix` and see if that solves it? Also, if you could check out the merge conflict in `src/redesign/components/Research.jsx`, that should be about it.

2024-04-11 15:03 UTC, NishantSatere commented
i have fixed the lint issue and merge conflict

2024-04-11 21:12 UTC, anth-volk requested changes
Unfortunately, it looks like this doesn't quite solve the issue. On most desktop displays, this works fine, but imagine a display that's very short. Unfortunately, the bottom of the list is still cut off. The video below demonstrates this behavior.

As such, could you find a way to either: 
1. Make sure the list only expands to the bottom of the page, or 
2. Allow the entirety of all menus to open simultaneously, and just add a scroll capability there (this is probably the better one)

Sorry, this didn't come across in your earlier video, but it could be an issue for some users.


https://github.com/PolicyEngine/policyengine-app/assets/14987227/60cf74c1-46a9-4fc5-9a26-38ceef096a2d

2024-04-11 21:12 UTC, anth-volk commented on src/redesign/components/Research.jsx
> +  // const [expanded, setExpanded] = useState(false);
```suggestion
```

2024-04-12 20:14 UTC, NishantSatere commented
i have made changes !

2024-04-12 20:20 UTC, anth-volk commented
Great! I will review first thing Monday. Thanks a lot, @NishantSatere.

2024-04-15 13:12 UTC, anth-volk requested changes
Thanks so much for this, @NishantSatere. While this is an improvement over the previous changes, this still has one particular issue: if the user has a short viewport, the bottom authors are still cut off. I demonstrate this in the video below.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/09787bf6-07fc-4ff8-951d-40b9d51aab58

I would encourage you to consider different viewport sizes as you make edits, as there's no longer any guarantee that users will have a particular screen size. In the case of these edits, I'd explore using a percentage-based height and potentially editing the height of the parent container to ensure that the menu never extends beyond the height of the screen.

2024-04-16 09:08 UTC, closed without merging

2024-04-16 13:11 UTC, anth-volk commented
@NishantSatere If you're still working on this, and not totally deleting your work, I would encourage converting this to a "draft" PR. There's a small link in the top-right of the PR page to do so that says, "Still in progress? Convert to draft". When you close the PR fully, it signals to us that you're either changing it very heavily or you no longer want to work on the issue.