Changed to ant design radio buttons
PolicyEngine/policyengine-app pull request #1600
Opened 2024-04-12 20:46 UTC by daemon-reconfig

## Description

this fixes: [#912 ](https://github.com/PolicyEngine/policyengine-app/issues/912)

## Changes

Changed to ant design radio buttons 

## Screenshots

<img width="688" alt="Screenshot 2024-04-13 at 2 15 37 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/69844188/86dd1d54-d39f-4855-8f5b-c14bea55ead0">

2024-04-12 21:06 UTC, anth-volk commented
I'm noticing that the border radius on this isn't quite squared off. Could you set it to 0? When we migrate to Ant Design v5, this will become much rounder, too much for our design.

2024-04-12 22:04 UTC, anth-volk commented
Could you run `make format` and push the results? We do require linting before merging in order to make for better code quality.

2024-04-13 03:14 UTC, daemon-reconfig commented
sure i will do so

2024-04-13 05:05 UTC, daemon-reconfig commented
<img width="644" alt="Screenshot 2024-04-13 at 10 34 29 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/69844188/f56e7bba-9072-4811-b9a3-899986f23e64">

here fixed

2024-04-13 05:29 UTC, daemon-reconfig commented
<img width="459" alt="Screenshot 2024-04-13 at 10 59 36 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/69844188/2376f874-cd76-4327-b695-0c67046cce75">

it gives this while linting

2024-04-13 17:44 UTC, MaxGhenis commented
Try `pip install black` first (see https://github.com/PolicyEngine/policyengine-app/issues/1602)

2024-04-13 19:39 UTC, daemon-reconfig commented
> Try `pip install black` first (see #1602)

thanks!

2024-04-15 18:03 UTC, daemon-reconfig commented
@anth-volk could you review this PR and merge it if it suits ?

2024-04-15 18:25 UTC, anth-volk commented
I will try to do so today, but am not sure if I'll be able to. It didn't appear that you'd run the linter, which is why I held off, but the code does pass all tests, so perhaps you had?

2024-04-15 18:54 UTC, daemon-reconfig commented
yes had linted the code

2024-04-17 13:12 UTC, anth-volk commented on package.json
> +    "black": "^0.3.0",
```suggestion
```

2024-04-17 13:26 UTC, anth-volk requested changes
Thanks for this, @daemon-reconfig. Just a couple of things:

1. If you run the code, you'll notice that the borders between the buttons are poorly defined, since they're a shade of gray. This is probably because of how Ant Design creates these borders. Could you instead iterate over the labels and generate individual `Radio.Button` elements to sit within one `Radio.Group`, and have any non-selected buttons have their own `style={{}}` prop that contains `border: "1px solid style.colors.WHITE"`?
2. This component currently doesn't manage styling statefully, instead always just making the background of the first element in the list blue and keeping the others gray. Could you use a standard state handling structure within `Radio.Group`'s `onChange` to save something (perhaps an index) to a stateful variable, then conditionally apply a background color to each `Radio.Button` within the `Radio.Group`? This will probably require a function that looks something like the following:

```
function handleChange(may need args here, depending on how Ant Design passes events) {

  Check if PolicyEngine's RadioButton's onChange prop is a function

  If so, run that function

  No matter what, update state to make this a controlled component
}
```

I've yet to actually test to make sure values are passed properly, but they appear to be.

Thanks again.

2024-04-17 13:26 UTC, anth-volk commented on package.json
> +    "black": "^0.3.0",
This package is different from the Python `black` linting package and should be uninstalled via `npm uninstall black` before recommitting

2024-04-18 04:27 UTC, daemon-reconfig commented
sure I will do the following changes.

2024-04-18 04:30 UTC, daemon-reconfig commented
if I uninstall that black I get error while linting

2024-04-18 12:07 UTC, daemon-reconfig commented
@anth-volk could you please elaborate what you want me to add in it

2024-04-18 12:14 UTC, daemon-reconfig commented
should I map radio.buttons? and 0th index will be the selected one the border of non selected should be changed to white
is this what you are talking about?
or I can change the border color of the non selected button to white

2024-04-18 13:33 UTC, anth-volk commented
The issue with `black` is partly on us, and it's being fixed in #1623. The `black` that you installed is a JavaScript package, but what contributors actually need is the Python package `black`, so if you could run `make install`, then `pip install -U black` for the time being, that should fix your issue. If that fails, please let me know.

2024-04-18 13:37 UTC, anth-volk commented
And yes, the borders should be white for all non-selected buttons, but what you have now for the selected button works. You should probably place `Radio.Group` into the main return statement, since you only need one of those, then map `Radio.Button`, but adding event change handling, akin to building a standard fully controlled React component. I could go more into detail if you're unfamiliar with this.

2024-04-18 14:20 UTC, daemon-reconfig commented
I had done pip install black when I installed it @MaxGhenis told me to.
an sure I will add an event handler for the buttons but I didn't get the thing about radio.button

2024-04-18 14:44 UTC, closed without merging

2024-04-19 03:24 UTC, daemon-reconfig commented
1. I am so sorry about it I did run `npm i black`
I will uninstall it.

2. I do know why we need states but I didn’t get why we should add `Radio.Button` as in the given reference there was no mention of it
https://ant.design/components/radio
But since you asked me to I will add them to it
what I did get is
• Adding a `Radio.Button` so that the first button would be selected which will have normal border- blue given by ant design itself 
• the second button which would be unselected should have white borders
• above two points should be achieved using states which will change the colors of the first button if it is unselected, i.e, second button was selected

my opinion: since we would not just be targeting two buttons using `Radio.Button` might not do it although we can map an array which will give us `Radio.Button`.

I deeply apologise if I caused any misunderstanding. 
I am thankful for your helpful messages and you have helped me learn a lot of things.

2024-04-19 15:21 UTC, anth-volk commented
1. Not a problem at all
2. Ant Design's documentation, unfortunately, isn't always amazing. I'm thinking `Radio.Button` would be better because with just the group, it seems a bit more difficult to manage state and to conditionally format the buttons. If you can get it to work with just `Radio.Group`, please feel free, that was just my read of the documentation.

2024-04-19 15:23 UTC, anth-volk commented
Also, in the future, if you're still working on an issue, please feel free to convert it to "draft" by clicking "Still in progress? Convert to draft" in the top right. Typically, if you close a PR, it looks like you no longer want to work on the issue.

2024-04-19 15:28 UTC, daemon-reconfig commented
sure I will add it to draft. 
also I think we can make do with `Radio.Group` and I will start working on implementing `Radio.Button` in it. as it may take time since I will have to research a bit into it.
or we can either go with more time taken but the end result would be getting a `Radio.Button`

2024-04-19 15:31 UTC, anth-volk commented
We're open to however you'd like to implement it, whichever way you think will work best.

2024-04-19 15:35 UTC, daemon-reconfig commented
sure will open a PR for it on Sunday. I have an exam tomorrow