Added conditional require statements for blog images on Home and Research pages.
PolicyEngine/policyengine-app pull request #1636
Opened 2024-04-23 17:05 UTC by czhou578

Fixes: #1629 

## Changes

Added conditional require statements for blog images on Home and Research pages. I also added a conditional check for some additional images on the Home page, as demonstrated through the following screenshots.

## Screenshots

## Home
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/507195e8-45a1-4a71-9b32-10505455b68e)
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/a7b3eefd-c828-444a-b554-9cfb47d14c33)
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/bfc7c8c3-4e9c-4648-a8db-ccad52034643)

## Research

![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/947faca6-8fca-4009-a9ad-9e60fcec7d04)

## Tests

No new tests were added.

2024-04-23 21:33 UTC, anth-volk commented
Here again, could you instead treat the icon like a thumbnail and place it in the bottom-right corner of a div that fills the space where the image would be?

2024-04-24 00:05 UTC, czhou578 commented
Is this acceptable?

![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/0e89b551-5200-487a-b109-493114fee8b6)
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/3e1044b9-61e1-407a-82a5-65d1265d873f)

2024-04-24 21:45 UTC, anth-volk requested changes
Thanks for this, @czhou578! This all looks great, just had some minor changes, and then I think this will be merge-able. Thanks again for your help with this.

2024-04-24 21:45 UTC, anth-volk commented on src/redesign/components/HomePolicyEngineFeatures.jsx
> +    console.log(imageSrc);
Could you remove this console log?

2024-04-24 21:45 UTC, anth-volk commented on src/redesign/components/HomeBlogPreview.jsx
> +    return require("../images/posts/" + path);
```suggestion
    return require("../../images/posts/" + path);
```

2024-04-24 21:45 UTC, anth-volk commented on src/redesign/components/HomeBlogPreview.jsx
> +    return require("../images/posts/" + path);
We're gradually trying to deprecate the `/redesign` folder, including its images, and the whole thing will be fully removed in an upcoming fix, but for now, this should reference the standard images folder, not the one inside `/redesign`

2024-04-24 21:45 UTC, anth-volk commented on src/redesign/components/ShowcaseItem.jsx
> +            // boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.9)",
Could you remove the commented styling?

2024-04-24 22:02 UTC, czhou578 commented
Fixed!

2024-04-25 13:46 UTC, anth-volk approved these changes
Thanks for the changes @czhou578! This is perfect and will help increase the stability of the application when errors occur.

2024-04-25 13:47 UTC, merged