Use Enhanced CPS when specified for Reproduce in Python Microsimulation call
PolicyEngine/policyengine-app pull request #1641
Opened 2024-04-26 14:33 UTC by shaunakwagh

## Description
Fixed #1624

## Changes

 Reproduce in Python gives a different code when enhanced CPS is enabled

 
## Screenshots
Before
<img width="1721" alt="Screenshot 2024-04-26 at 10 18 57 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/34841979/26284fc4-22f5-4745-aa2b-0d0c7bcc98b3">
After
<img width="1719" alt="Screenshot 2024-04-26 at 10 19 12 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/34841979/812de188-d0d3-4063-a175-48a373e93272">

## Tests
No test added

2024-04-26 15:19 UTC, anth-volk commented
I believe you have two sets of changes in this branch, one which is for #1624, and one which is for #1640. Could you separate these and ensure that this PR is just for #1624?

2024-04-26 15:27 UTC, shaunakwagh commented
i removed the changes for #1640

2024-04-26 15:50 UTC, anth-volk commented
Will review a bit later today

2024-04-28 04:49 UTC, shaunakwagh commented
any updates ?

2024-04-29 14:12 UTC, anth-volk commented
My apologies, somehow I missed this. Will review in a few.

2024-04-29 14:58 UTC, anth-volk requested changes
Thanks for this, @shaunakwagh. While I appreciate that you anticipated the code incorrectly setting the year, the enhanced CPS flag actually has to be set to 2022. Could you change that then re-request review? After that, this should be good to go.

2024-04-29 14:58 UTC, anth-volk commented on src/data/reformDefinitionCode.js
> +        ? `reform=reform, dataset="enhanced_cps_${timePeriod}"`
```suggestion
        ? `reform=reform, dataset="enhanced_cps_2022"`
```

While your assumption that this should change by year makes a lot of sense, I believe it is actually meant to map to 2022 specifically. If you try a different year in your version of the code and run the output in Google Colab, for example, you receive the following error:

```
ValueError: Dataset enhanced_cps_2023 not found. Available datasets: ['cps_2019', 'cps_2020', 'cps_2021', 'cps_2022', 'enhanced_cps_2022', 'calibrated_puf_extended_cps_2022', 'poverty_tracker', 'puf_2022', 'puf_2015']
```

2024-04-30 10:35 UTC, anth-volk approved these changes
Thanks so much, @shaunakwagh! This is now what we're looking for.

2024-04-30 10:35 UTC, merged