Repair errors in Reproduce in Python
PolicyEngine/policyengine-app pull request #1783
Opened 2024-05-15 21:31 UTC by anth-volk

## Description

Fixes #1782.

## Changes

Fixes two errors in the Reproduce in Python block: sanitizes outputs to ensure that reform code uses Python `True`, `False`, and `None`; and removes an error that prints `dataset=` twice when using `enhanced_cps` for calculations.

## Screenshots

<img width="1440" alt="Screen Shot 2024-05-15 at 11 27 35 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/be7751fb-2053-4aee-aabd-38fa5463e013">

## Tests

None have been added.

2024-05-15 22:17 UTC, MaxGhenis requested changes
Could you move some of this to a helper function to reduce duplication?

2024-05-16 12:34 UTC, nikhilwoodruff approved these changes
Agree with @MaxGhenis' comment

2024-05-16 15:44 UTC, anth-volk commented
The PR has been updated to refactor the Python sanitization into a utility function and to test said function.

2024-05-16 16:14 UTC, MaxGhenis approved these changes

2024-05-16 16:14 UTC, merged