Explicitly mentions the useage of enhanced CPS in the AI prompt when use enhanced CPS is  toggled #1856
PolicyEngine/policyengine-app pull request #1944
Opened 2024-08-03 07:38 UTC by bharateshwq

## Description

Adds Explicit descriptors to the AI prompt when enhanced CPS is turned on

## Changes

The code checks if enhanced CPS for USA is turned on and explicitly adds a descriptor to the AI prompt

2024-08-04 22:02 UTC, anth-volk commented
@bharateshwq Could you run `make format` and push the code again?

2024-08-06 02:56 UTC, bharateshwq commented
Hey @anth-volk Ive ran make format and pushed the code again

2024-08-06 23:56 UTC, anth-volk commented
@bharateshwq Perfect! Thanks, will review later today.

2024-08-07 05:47 UTC, anth-volk requested changes
Thanks so much for your contribution! Just one minor change, and then this should be good to merge.

2024-08-07 05:47 UTC, anth-volk commented on src/pages/policy/output/promptContent.js
> +       "*  Explicitly mention that This analysis uses PolicyEngine's Enhanced CPS, constructed from the 2022 Current Population Survey and the 2015 IRS Public Use File, and calibrated to tax, benefit
```suggestion
       "*  Explicitly mention that this analysis uses PolicyEngine's Enhanced CPS, constructed from the 2022 Current Population Survey and the 2015 IRS Public Use File, and calibrated to tax, benefit, income, and demographic aggregates."
```

Just a minor change for grammatical reasons

2024-08-09 18:08 UTC, anth-volk commented
@bharateshwq Looks like you also merged your virtual environment. Could you either delete that, move it to a new folder, or rename it to `venv` and add `venv/*` to `.gitignore`? You'll also have to run `git reset venv` to remove it from git tracking.

2024-08-09 18:16 UTC, bharateshwq commented
hey @anth-volk ive deleted them now,
thank you for being patient

2024-08-09 18:31 UTC, anth-volk commented
@bharateshwq I'm sorry, this still contains the capitalized "This" that was an issue before

2024-08-09 18:42 UTC, anth-volk approved these changes
@bharateshwq Thanks for your contribution to this! All looks good.

2024-08-09 18:43 UTC, merged

2024-08-24 18:57 UTC, AKANKSHBC approved these changes

2024-08-24 19:15 UTC, anth-volk commented
Hi @AKANKSHBC. While we are an open-source project open to contributors from all backgrounds, we typically prefer to work one-on-one with contributors before granting them the ability to approve PRs. I'm not sure how you were able to grant approval, to be honest. If you'd like to contribute in a meaningful way, whether it be writing new features or anything else, please respond here indicating your interest and we can work out a way to connect. Otherwise, please avoid approving PRs and doing any other administrative tasks moving forward.