Flatten tree and handle error when focus not found in DOM
PolicyEngine/policyengine-app pull request #1947
Opened 2024-08-08 00:07 UTC by rachel-lawrie

DO NOT MERGE YET. Proof of concept for fixing issue 1814 https://github.com/PolicyEngine/policyengine-app/issues/1814

## Description

This solution addresses https://github.com/PolicyEngine/policyengine-app/issues/1814. It is not fully baked yet but I am sharing now to ensure it is on the right track before I continue.

## Changes

1. Added a helper function to flatten the tree in https://github.com/PolicyEngine/policyengine-app/blob/master/src/pages/policy/output/tree.js
2. Added error handling that checks that the new focus is present in https://github.com/PolicyEngine/policyengine-app/blob/master/src/pages/policy/output/ImpactTypes.jsx. If it is not present, then the focus is updated to the next index.  

## Screenshots

https://www.loom.com/share/2b8058e1f02f4a80808c879a6bcd49f3?sid=3aa0cc60-b51f-410b-931c-ed74d0bb0743

## Tests

This has not yet been tested and should not be merged yet. Notes on additional points to think through:
- Are there other scenarios where focus is updated and similar logic needs to be added?
- Need to test last index
- Need to edit code for the previous arrow

2024-08-08 00:13 UTC, anth-volk commented
One thing before reviewing: could you add your virtual environment to the `.gitignore`?

2024-08-08 01:46 UTC, MaxGhenis commented
Please mark as draft

2024-08-08 04:31 UTC, MaxGhenis commented on .gitignore
> +venv/
could solve the large diff
```suggestion
venv/*

```

2024-08-08 15:42 UTC, rachel-lawrie commented on .gitignore
> +venv/
Thank you!

2024-08-08 16:38 UTC, MaxGhenis commented
Could you edit the description to use keywords that link the pr to the issue? https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-08-08 18:46 UTC, anth-volk commented
@rachel-lawrie Max meant could you keep the same title you had, but in the first line in your PR description, add:

Fixes #1814

2024-08-08 19:46 UTC, anth-volk reviewed
Just went through this, thanks @rachel-lawrie! Here are a few thoughts:

* I think the tree flattening code you utilize works well for determining what the right arrow should lead to. However, if you try accessing a breadcrumb in the middle of the tree, the code crashes. Could you keep the flattening for the arrows, but add a component similar to `FolderPage` (this could even mean just making `FolderPage` more generalizable) for the mobile view only so that users can navigate through?
* This isn't related to the tree flattening, but could you remove the extra `BottomCarousel` component in the picture below (this probably means adding code that checks if the user's on mobile, and if so, doesn't show it) and widen the navigation buttons to be the same width as the other buttons on that menu?

Also, if you think the breadcrumbs should sit elsewhere, such as above the buttons in a row, please feel free to implement.

Thanks so much for your work on this! We really appreciate your enthusiasm and your contributions.

2024-08-08 20:08 UTC, MaxGhenis commented on .gitignore
> +venv/*
We generally keep an empty newline in all files https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
```suggestion
venv/*

```

2024-08-09 19:53 UTC, rachel-lawrie commented
Update: Arrows now work. I am meeting with Anthony to ensure test plan is comprehensive prior to merge.

2024-08-16 02:54 UTC, anth-volk requested changes
Thank you very much for this contribution @rachel-lawrie. I just had some pretty brief changes to request to fix some linting concerns. Otherwise, this looks great! Looking forward to getting merged.

2024-08-16 02:54 UTC, anth-volk commented on src/__tests__/pages/household/output/HouseholdMobileCalculator.test.js
> +import { render, screen, cleanup, fireEvent } from "@testing-library/react";
```suggestion
import { render, screen, fireEvent } from "@testing-library/react";
```

2024-08-16 02:54 UTC, anth-volk commented on src/__tests__/pages/household/output/HouseholdMobileCalculator.test.js
> +              expect(prevButton).toBeInTheDocument();
Throughout this test, the linter returns a warning not to place `expect()` inside a conditional, as there are cases where errors thrown by the code aren't recognized. Could you refactor this, even if it involves writing three separate tests, one for `index[0]`, one for `index[length - 1]`, and one for all others?

2024-08-16 02:54 UTC, anth-volk commented on src/__tests__/pages/household/output/HouseholdMobileCalculator.test.js
> +              expect(prevButton).toBeInTheDocument();
Alternatively, if you write a small helper function that just checks the index and determines what should be returned, then `expect`ed the output of that function (something like `expect(sampleFunc(prevButton))`, and then have `sampleFunc(arg)` selectively either return `null` or the original `arg`

2024-08-16 02:54 UTC, anth-volk commented on src/layout/MobileCalculatorPage.jsx
> +import { impactKeys } from "../pages/policy/output/ImpactTypes.jsx";
I couldn't add the comment at the correct line, but could you remove line 17 (`import {copySearchParams}...`) if it's no longer called?

2024-08-16 02:54 UTC, anth-volk commented on src/layout/MobileCalculatorPage.jsx
> +  let previous, next;
Could you explicitly instantiate these to `null`?

2024-08-21 03:30 UTC, anth-volk requested changes
There's an error in this that I didn't notice before. For some reason, despite the fact that it's included in `tree.js`, the `codeReproducibility` (Reproduce in Python) component does not show up for me as an option within the arrows. Once the user clicks through to the AI Analysis page, the right arrow is no longer visible, and thus there's no way to actually visit the Reproduce in Python page on mobile.

2024-08-22 03:29 UTC, anth-volk approved these changes
Just ran through a review and this all looks great! Thanks again for your contributions here, @rachel-lawrie!

2024-08-22 03:29 UTC, merged