consitent ux for show profile and hamburger
PolicyEngine/policyengine-app pull request #1998
Opened 2024-09-01 06:10 UTC by bharateshwq

## Description

This pull request addresses the inconsistent user experience observed in the profile dropdown functionality. Previously, the profile dropdown was activated on hover, which was inconsistent with the hamburger menu behavior and other common practices found in similar applications 

## Changes

Changed the activation method for the profile dropdown from onHover to onClick in the header. This aligns the interaction model with the hamburger menu and improves consistency with standard UX practices.

2024-09-01 06:26 UTC, bharateshwq commented
https://github.com/user-attachments/assets/e0210eef-dfcc-427c-a5e7-925560679752

2024-09-02 13:19 UTC, anth-volk commented
I'm sorry, but could you format it as "Fixes #1958"? Otherwise it won't be captured.

2024-09-02 13:35 UTC, anth-volk requested changes
Thanks for your contribution @bharateshwq. Left a suggestion, since mobile and desktop behavior would now be the same.

2024-09-11 01:33 UTC, anth-volk approved these changes
@bharateshwq Thank you for your work on this. I took the liberty of merging a commit that removed an unused variable.

2024-09-11 01:33 UTC, merged