Developer Tools page
PolicyEngine/policyengine-app pull request #2046
Opened 2024-09-29 15:58 UTC by bharateshwq

## Description

Fixes #2035

Created basic wire frame design for how the developer tools should look like while keeping in consideration the design language of policy Engine
Let me know if there are changes required for this

This in no way is the final commit that i expect to be merged there are a lot of optimization, responsiveness tasks and restructuring to be 

## Screenshots

![image](https://github.com/user-attachments/assets/050eab73-8f4e-473b-ab65-f549ce26efba)

2024-09-30 16:35 UTC, bharateshwq commented
Hey @MaxGhenis , 
I have pushed a new commit can you have a look at it

2024-09-30 16:59 UTC, anth-volk commented
@bharateshwq This is looking great! Thanks for your work on it. Could you just do the following on the design:

* Pad the titles underneath the images more on the top, perhaps to about 1rem
* Show how this looks on tablet (769 to ~1200px) and mobile (<769px) breakpoints

I might also ask for a couple changes to the text of the header afterward

2024-10-01 18:33 UTC, bharateshwq commented
Hey @anth-volk,
I have done the necessary changes and added responsiveness to the developer-hub page

2024-10-02 16:44 UTC, anth-volk requested changes
Thanks for your work on this @bharateshwq, this is looking good. There are a few changes I was hoping to request:

* At the moment, this code places a wrapper around the API status and simulations pages. Could you remove that, including the "back" arrow? The pages themselves should actually be unchanged.
* Could you link this page into the footer with the tag "Developer tools"?
* Minor, but could you add padding to the right of the text within the link boxes at the mobile viewpoint? In the image below, you can see how the word "Simulations" runs into the button.
<img width="579" alt="Screen Shot 2024-10-02 at 5 57 36 PM" src="https://github.com/user-attachments/assets/3c84f01c-395c-4949-8f6b-02b496474fc6">

I might also request some textual changes, but am hoping to do that at the end.

2024-10-02 16:54 UTC, bharateshwq commented
Hey @anth-volk, 

I'll definitely fix that. Do you prefer having the `api-status` route separate, or keeping it under `developer-tools/api-status`? Right now, it's the latter, in which case users might find it more intuitive to have a back button on the API status and simulation pages. Let me know your thoughts!

2024-10-02 17:13 UTC, anth-volk commented
@bharateshwq I think the way you layered the URLs makes sense, but I also think their browser back button should be able to handle that navigation action, as I believe `react-router-dom` writes to history.

2024-10-02 17:29 UTC, bharateshwq commented
Yes @anth-volk, React Router does write to the history, so using the browser's back button would work for navigation. However, I'll be removing the back button from the UI. Additionally, the current(master) API status and simulation headers  have different designs, which I feel may not appear consistent to the user.
How would you like me to proceed with this?

2024-10-02 17:44 UTC, anth-volk commented
@bharateshwq That is a good point. Considering these are internal developer tools, I don't think it's too big of an issue, but certainly warrants opening a separate issue. I can't remember their designs well enough, but I'm guessing the API status page is more out-of-line with our current design. If you'd like to take it on after this one, we'd greatly appreciate it.

2024-10-05 15:51 UTC, bharateshwq commented
Hey @anth-volk, I've made the updates as requested and am awaiting your feedback. Thanks!

2024-10-05 20:55 UTC, anth-volk commented
@bharateshwq Thanks, I'm hoping to get to this either tonight or tomorrow

2024-10-07 21:16 UTC, anth-volk requested changes
Hey @bharateshwq. Thanks again for your work on this, this will be a major benefit for internal development. I've left a couple of minor change requests, and also took the liberty of cleaning up a merge conflict/linting. After this, we should be good to merge!

2024-10-07 21:16 UTC, anth-volk commented on src/layout/Footer.jsx
> +      label: "Developer tools",
```suggestion
      label: "Developer Tools",
```

2024-10-07 21:16 UTC, anth-volk commented on src/pages/DeveloperHome.jsx
> +    console.log("Scrolling to top on pathname change:", pathname);
```suggestion
```

2024-10-07 21:16 UTC, anth-volk commented on src/pages/DeveloperHome.jsx
> +        // maxWidth: "1000px", // Set a max width for ToolBox
```suggestion
```

2024-10-07 21:16 UTC, anth-volk commented on src/pages/DeveloperHome.jsx
> +function ToolsStruct({
Just personal preference: structs do exist in JS (albeit more as a concept) could you change this name?

2024-10-07 21:16 UTC, anth-volk commented on src/pages/DeveloperHome.jsx
> +            {/* <div>{bottomLeft}</div> */}
```suggestion
```

2024-10-07 21:16 UTC, anth-volk commented on src/pages/DeveloperLayout.jsx
> +            Welcome to the Developer Tools page for PolicyEngine! This hub is
```suggestion
            Welcome to the Developer Tools page for PolicyEngine. This hub is
```
Having fun is not allowed in tax and benefit simulation

2024-10-13 09:48 UTC, bharateshwq commented
Hey @anth-volk ,
sorry for the late reply i have sent a new commit with all suggested changes

2024-10-15 18:51 UTC, anth-volk requested changes
Thanks for your work on this @bharateshwq, it's looking great.

Earlier, when I had asked that you remove the enclosing features, it was because it created a wrapper that added a "back" button and created two footers. We actually still want the "header" (the navbar) and the footer, just not the back button. Could you add the navbar back into these two pages?

After that, this will be good to go.

2024-10-20 13:54 UTC, bharateshwq commented
Hey,
i have made a new commit fixing this

2024-10-21 23:36 UTC, anth-volk commented
@bharateshwq I've taken the liberty of addressing some merge conflicts in the PR. I'll approve and merge once tests pass.

2024-10-21 23:47 UTC, anth-volk approved these changes
Thank you very much @bharateshwq! Merging now.

2024-10-21 23:47 UTC, merged