behavorial-response-post
PolicyEngine/policyengine-app pull request #2191
Opened 2024-11-05 11:07 UTC by vahid-ahmadi

I wrote a post about how we enhanced our modelling with behavioural responses, including income, substitution and capital gains elasticities.

Fixes #2190

2024-11-05 11:18 UTC, nikhilwoodruff reviewed
LGTM- holding off for Max's review

2024-11-05 23:26 UTC, MaxGhenis requested changes
main suggestions/comments in the [doc](https://docs.google.com/document/d/1_073b_pz6p4HubGT06VX_TuEN_YpDXzDHOi2gTqVSbc/edit?tab=t.0)

2024-11-05 23:26 UTC, MaxGhenis commented on src/posts/posts.json
> +    "tags": ["uk", "policy", "elasticity", "featured"],
```suggestion
    "tags": ["uk", "policy", "behavioural-responses", "featured"],
```

2024-11-11 04:43 UTC, MaxGhenis approved these changes
good to merge after these changes

2024-11-11 04:43 UTC, MaxGhenis commented on src/images/posts/behavorial-post.jpg
rename `behavioural-responses.jpg`

2024-11-11 04:43 UTC, MaxGhenis commented on src/posts/articles/behavioural-response-post.md
rename `behavioural-responses.md`

2024-11-11 04:43 UTC, MaxGhenis commented on src/posts/posts.json
> +    "description": "PolicyEngine has enhanced its modelling with behavioural responses, including income, substitution and capital gains elasticities.",
```suggestion
    "description": "PolicyEngine has enhanced its modelling with behavioural responses regarding earnings and capital gains.",
```

2024-11-11 09:39 UTC, merged