Increase logo size and adjust container width
PolicyEngine/policyengine-app pull request #872
Opened 2023-11-23 15:41 UTC by pkvijay65

**Title:**
Enhance Logo Size and Layout in "Trusted Across the US" Section (#869)

Description:
Refined the sizing and distribution of logos within the "Trusted Across the US" section to address concerns about their scale compared to the UK site.

**Changes:**

- Enlarged logos for enhanced visibility and uniformity with the UK site.
- Applied space-around in the flex container for better spacing on wider screens.
- Shifted to a max-width approach for dynamic logo size adjustment.

**Visuals:**
**Before Change for US Site:**
![image](https://github.com/PolicyEngine/policyengine-app/assets/113239008/d73147d2-f759-4fdb-9601-b4802542ae2f)

**After Change for US Site:**
![image](https://github.com/PolicyEngine/policyengine-app/assets/113239008/c1d2befe-f639-40cb-975e-c2ebae29a18e)

**Before Change for UK Site:**
![image](https://github.com/PolicyEngine/policyengine-app/assets/113239008/ec7bb0ec-f317-4298-a2e8-a0015d7d971b)

**After Change for UK Site:**
![image](https://github.com/PolicyEngine/policyengine-app/assets/113239008/a23c0b4c-40a2-4602-b0d6-010ddeccf045)

**Discussion Point:**
While addressing the issue of the smaller logos on the US site, I also observed that the logos appear smaller on the UK site too. So, I have done resizing universaally and they look ok to me. Should our adjustments be universally applied across both sites for consistency, or should we consider separate sizing strategies for each site based on logo sizes for both the countries?

2023-11-23 20:39 UTC, anth-volk commented
My personal view would be that it would be better if they were consistently the same size across sites. That said, it's always seemed to me that the logos on the US site look smaller than the ones on the UK. At present, I'm wondering if we size based purely on width, or if we treat each as a square and if maybe that causes the US ones to look smaller.

2023-11-27 01:16 UTC, MaxGhenis commented
I agree with consistency across countries although I don't think anyone except the dev team looks at multiple countries, so if this change makes each country homepage look better without creating significant gaps across countries it seems worth merging

2023-12-11 23:33 UTC, anth-volk commented
Hey @pkvijay65, apologies for the delay in re-addressing this. Would you be willing to rebase off main? If there are any merge conflicts, I'm happy to handle those

2023-12-11 23:34 UTC, anth-volk requested changes
Hey @pkvijay65, apologies for the delay in re-addressing this. Would you be willing to rebase off main? If there are any merge conflicts, I'm happy to handle those

2023-12-30 00:07 UTC, anth-volk commented
Closing as stale in favor of contributions from a different contributor.

2023-12-30 00:07 UTC, closed without merging