Restrict the Marginal Tax Rates axis range to `[-200%, 200%]`.
PolicyEngine/policyengine-app pull request #977
Opened 2023-12-18 16:38 UTC by abhcs

Fix #66 by filtering function values that exceed `200%` or go under `-200%`.

Tested against [this household](https://policyengine.org/us/household?focus=householdOutput.mtr&household=38027).

View when current income is `0`:

<img width="743" alt="Screenshot 2023-12-18 at 10 25 23 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/341d9cc4-a907-4d06-832c-32567568be95">

View when current income is `14,000`:

<img width="743" alt="Screenshot 2023-12-18 at 10 26 52 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/fe93c639-f746-4a0d-bde9-d81f8556e925">

Thus, when the value corresponding to the current income does not lie in `[-200%, 200%]` the range on the y-axis is extended to include the value.

2023-12-18 19:20 UTC, abhcs commented
There are two peaks above `200` but we ignore them, so the range of y-values is `[-90, 70]`. We add a padding of `0.1 x (70 - (-90)) = 16'. The padded range of `[-106, 86]' is displayed. The mentioned calculations are approximations.

2023-12-18 19:38 UTC, anth-volk commented
Gotcha. @MaxGhenis do you feel the 100% axis should be displayed if there are any values above it? I would personally lean toward it.

2023-12-18 21:20 UTC, abhcs commented
Just thinking about it a bit, if most of the values are within say `[0,10]` and there is one outlier of `700`, then the current design would keep the axis range around `[0,10]` with some padding, which is desirable, I think. In such a case, having a forced range of `[0,100]` would shrink the features.

The MTR function displayed in the chart is multidimensional with a vast domain. Still, we are making decisions about how to display the function based on a few samples from the domain, i.e., viewing the website for a particular household. This is a bit dangerous and the magic constants like `200` and `100` may not work for other households.

A more robust solution would be to find the outliers in the back end without relying on constants (I have code for this by using a Python lib for 1-D clustering). However, this would require changes to the API. Therefore, I have gone ahead with the current PR.

All that being said, I am happy to add the `100` constant too.

2023-12-20 18:24 UTC, MaxGhenis commented
Hi sorry I'm getting to this late. Can we instead set the y axis limits, rather than the values? So take the bounds of the data, add e.g. 10% on either side, and then clip those bounds at +/-200% for setting y axis limits, but leave the values as they are.

2023-12-20 18:32 UTC, anth-volk requested changes
Per Max:

Can we instead set the y axis limits, rather than the values? So take the bounds of the data, add e.g. 10% on either side, and then clip those bounds at +/-200% for setting y axis limits, but leave the values as they are.

Thanks so much for your work on this, @abhcs.

2023-12-20 18:32 UTC, abhcs commented
We *are* changing axis limits and not values in this PR. In the two examples posted in the initial comment, do you expect to see something else? Please clarify.

2023-12-20 21:13 UTC, anth-volk commented
He had been thinking a modification to the code that, instead of merely filtering values outside of the bounds, would determine if values exist above and/or below, and then set the upper and lower bounds at +/- 2 accordingly, as merely filtering dynamically sets the chart range based upon the remaining values

2023-12-21 00:44 UTC, abhcs commented
Screenshots after the latest changes for the same household with different incomes:

For income = `0`:
<img width="795" alt="0" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/e7dba64f-d22e-47a6-b781-52db99f98e00">

For income = `14,000`:
<img width="795" alt="14k" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/2f795ca0-b7cb-4943-8875-df812663f9e8">

For income = `55,000`:
<img width="795" alt="55k" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/aec50546-2918-4d5f-b15a-275a4c7b4a9e">

2023-12-21 02:30 UTC, MaxGhenis commented
can we trim the 735% example too?

2023-12-21 02:51 UTC, abhcs commented
We can but the current behavior is by design! If we were to trim the 735% case, then 
- the dark blue circle representing the current MTR would not be visible on the graph, and
- double-clicking the current MTR legend would just yield an empty graph.

I have kept the current values visible in the chart to avoid this behavior. An alternative could be to not display the current value and the legend and still trim! Please let me know if you want this.

2023-12-22 14:09 UTC, MaxGhenis commented
Ok sounds good let's try this and we can come back to it if it's confusing

2023-12-29 21:21 UTC, anth-volk approved these changes
This looks great and works well on my side, @abhcs. Thanks so much for your contributions!

2023-12-29 21:21 UTC, merged